### ISSUE TITLE
palette bug with the slots for colors

### ISSUE THREAD

**Issue by InsaneAwesomeTony** [Orama-Interactive/Pixelorama#1356]
**Pixelorama version:**
1.1.5. stable

**Where did you download Pixelorama from?**
Flatpak

**OS/device including version:**
Fedora 42

**Issue description:**
displays empty/extra colors in palettes. Imported some palettes using the PNGs format. for palettes that's not a multiple of 8 (8,16,24,32 etc), shows extra and empty slots. really weird. also those 8 slots per row doesn't adapt to the resizing of the palette dock. creating unnecessary empty space

<img width="418" height="199" alt="Image" src="https://github.com/user-attachments/assets/ab1236f0-bdf0-40fa-9764-b14e8a55db98" />

<img width="418" height="199" alt="Image" src="https://github.com/user-attachments/assets/0cfc7136-94f9-4d11-9dcf-d64c95f448d3" />

Empty space:

<img width="418" height="282" alt="Image" src="https://github.com/user-attachments/assets/30dfd899-97d0-4d82-af9d-4ccb42fb5368" />

**Comment by OverloadedOrama** [comment]
Thanks for reporting! I fixed the empty swatch when importing issue a while back in cdab4487717906dd12e560e612386b32580b03e6 and the fix is already included in the current stable version (v1.1.6)

As for the fact that the palette grid doesn't adapt to the empty space, this is in fact by design and is not an issue. Palettes have a fixed width and height in order to always appear the same, if the colors are grouped in a certain way, such as each row being multiple shades of the same color. However, I went ahead and added a button that lets users turn off this behavior and "unlock" the grid, making it resize and fill the empty space in 966a5b082d168966cd3c98ecc036c4141d6c8a2a. This feature will be included in the next stable version, v1.1.7.

**Comment by InsaneAwesomeTony** [comment]
wow, thanks! 
I still got the bug tho. but looking at cdab448, i figured out the problem and a quick fix. the palette i found on lospec is png-32x so it's bigger than one and empty swatches still appear. 
how to solve this: edit currently selected palette --> change height from 2 to 1 and it will fix itself :D 

why did i download 32x pngs? i dont know. opening them in regular image viewer and it's always so small and hard to see so i went with bigger :S what a mistake that was 😓 

EDIT: some worked as you described, some of the smaller ones. the longer ones didn't. at first i thought that it might be because they weren't new but already palettes that i added but new ones also act weirdly like that 😵‍💫 

and the quick fix doesn't work anymore? i'm majorly confused and i'm sorry i cant be of any more help
two problem palettes in the discord server --> pixelorama-dev
I just did some surface level testing so didn't really try anymore than those two and a few smaller ones trying to narrow down the problem 🤔
